

###################  项目启动端口  ###################
server:
  display-name: Demo-ADMIN
  port: 8888
  error:
    whitelabel:
      enabled: false
  compression:
    min-response-size: 512 #压缩文件最小大小(kb)
    enabled: true #是否压缩
    mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg


###################  spring配置  ###################
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .ftl
  freemarker:
    template-loader-path: classpath:/templates/, classpath:/templates/*
    cache: false
  http:
    encoding:
      force: true
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  application:
    name: Demo-ADMIN
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources,classpath:/static/,classpath:/public/,file:${oa.file-upload-path}
    chain:
      cache: true
      gzipped: true
    cache-period: 60
  aop:
    auto: true
    proxy-target-class: false
  datasource:
      url: jdbc:mysql://localhost:3306/wt-pro?useUnicode=true&characterEncoding=utf-8
      username: dev
      password: dev123456

      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      # druid 配置
      druid:
        #初始化连接大小
        initialSize: 8
        #最小空闲连接数
        minIdle: 5
        #最大连接数
        maxActive: 10
        WebStatFilter:
          enabled: true
#    activiti:
#      async-executor-activate: true
#      check-process-definitions: false

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.wt.**.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true